remote_theme: brunochanrio/mkdocs-jekyll@1.2.1
plugins:
- jekyll-remote-theme

title: Listas IPTV de Mametchi Kitty 
logo: "mametchikitty.png"
author: Mametchi Kitty 



baseurl: "/Listas-IPTV"
color: "#1DE9B6"
accentColor: teal
themeColor: pink
fixedNav: 'false' # true or false

github_user: mametchikitty
instagram: ale.el.kiki
threads: "@ale.el.kiki"

permalink: /:year/:title/
markdown: kramdown
exclude: [_site, CHANGELOG.md, LICENSE, vendor]

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path

# Defaults
defaults:
  - scope:
      path: "_docs"
      type: "docs"
    values:
      layout: page
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "posts"
      type: "posts"
    values:
      layout: "post"
